#!/usr/bin/env bash

#get name of the current directory
NAME=$(basename "$PWD")

#run the docker
docker run --rm --name $NAME --network robomatic -p 8080:8080 -v /home/edgar/robomatic/github/evidence:/home/evidence -v /home/edgar/robomatic/github/cases:/home/cases $NAME
